plugins {
    id 'com.android.application'
}

android {
    namespace 'dev.aut.usbping'
    compileSdk 36

    defaultConfig {
        applicationId 'dev.aut.usbping'
        minSdk 23
        targetSdk 36
        versionCode 25
        versionName '1.1.0'
    }
}

dependencies {
    implementation 'com.google.android.material:material:1.13.0'
}
