plugins {
    id 'com.android.application'
}

android {
    namespace 'dev.aut.usbping'
    compileSdk 36

    defaultConfig {
        applicationId 'dev.aut.usbping'
        minSdk 23
        targetSdk 36
        versionCode 21
        versionName '0.9.1'
    }
}

dependencies {
    implementation 'com.google.android.material:material:1.13.0'
}
